*** Settings ***
Resource    common.resource
Resource    pages/login_page.resource
Resource    pages/dashboard_page.resource
Resource    pages/register_page.resource
Resource    pages/class_page.resource
Resource    pages/student_page.resource
Resource    pages/attendance_page.resource
Resource    pages/schedule_page.resource
Resource    pages/timetable_page.resource
Resource    pages/report_page.resource
Resource    services/api_flows.resource
